version: 2
jobs:
  build:
    working_directory: ~/myshoggoth
    docker:
      - image: fpco/stack-build
    branches:
      only:
        - hakyll
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "myShoggoth.cabal" }}
            - stack-work-
      - run:
          name: Build site executable
          command: stack build
      - save_cache:
          paths:
            - ~/myshoggoth/.stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "myShoggoth.cabal" }}
      - initialize_submodules:
          name: Prepare the git submodules
          command: |
            git submodule init
            git submodule update
      - checkout_master:
          name: Checkout the master branch (live site)
          working_directory: ~/myshoggoth/_site
          command: |
            git checkout master
            git pull origin master
            git rm -rf .
      - build_site:
          name: Create the site
          working_directory: ~/myshoggoth
          command: stack exec -- myShoggoth build
      - commit_master:
          name: Commit the updated site
          working_directory: ~/myshoggoth/_site
          command: |
            git status
            git add -all
            git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
            git push origin master
      - commit_hakyll:
          name: Commit the hakyll branch
          working_directory: ~/myshoggoth
          command: |
            git status
            git add _site/
            git commit -m "Update _site (`date '+%F %T %Z'`) [ci skip]"
            git push origin hakyll
