version: 2
jobs:
  build:
    working_directory: ~/myshoggoth
    docker:
      - image: fpco/stack-build
    branches:
      only:
        - hakyll
    steps:
      - add-ssh-keys
        fingerprints:
          - "ee:d1:80:91:a3:b6:af:28:59:4d:de:a0:41:5a:56:3e"
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "myShoggoth.cabal" }}
            - stack-work-
      - run:
          name: Build site executable
          command: stack build
      - save_cache:
          paths:
            - ~/myshoggoth/.stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "myShoggoth.cabal" }}
      - run:
          name: Prepare the git submodules
          command: |
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI
            git submodule init
            git submodule update
      - run:
          name: Checkout the master branch (live site)
          working_directory: ~/myshoggoth/_site
          command: |
            git checkout master
            git pull origin master
            git rm -rf .
            ls -alF
      - run:
          name: Create the site
          working_directory: ~/myshoggoth
          command: |
            stack exec -- myShoggoth build
            ls -alF
      - deploy:
          name: Commit the updated site
          working_directory: ~/myshoggoth/_site
          command: |
            git status
            git add --all
            git commit -m "Update (`date '+%F %T %Z'`) [ci skip]"
            git push origin master
      - run:
          name: Commit the hakyll branch
          working_directory: ~/myshoggoth
          command: |
            git status
            git add _site/
            git commit -m "Update _site (`date '+%F %T %Z'`) [ci skip]"
            git push origin hakyll
