version: 2
jobs:
  build:
    working_directory: ~/myshoggoth
    docker:
      - image: futtetennista/hakyll:latest
    branches:
      only:
        - hakyll
    steps:
      - add-ssh-keys:
          fingerprints:
            - "ee:d1:80:91:a3:b6:af:28:59:4d:de:a0:41:5a:56:3e"
      - run:
          name: Disable prompting for host etc.
          command: |
            mkdir -p ~/.ssh
            cat << EOF > ~/.ssh/config
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile=/dev/null
EOF
            chmod 0400 ~/.ssh/config
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "myShoggoth.cabal" }}
            - stack-work-
      - run:
          name: Build site executable
          command: |
            stack setup
            stack build
      - save_cache:
          paths:
            - ~/myshoggoth/.stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "myShoggoth.cabal" }}
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            stack exec myShoggoth rebuild
            git checkout master
            git pull --rebase
            # Overwrite existing files with new files
            cp -a _site/. .
            #  Commit
            git add --all
            git commit -m "[`date '+%F %T %Z'`] New release"
            # Push
            git push origin master:master
