version: 2
jobs:
  build:
    working_directory: ~/myshoggoth
    docker:
      - image: futtetennista/hakyll:latest
    branches:
      only:
        - hakyll
    steps:
      - add-ssh-keys:
          fingerprints:
            - "ee:d1:80:91:a3:b6:af:28:59:4d:de:a0:41:5a:56:3e"
      - run:
          name: Add ssh for github for some strange reason
          command: |
            mkdir -p ~/.ssh
            echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
      - checkout
      - restore_cache:
          keys:
            - v1-stack-{{ checksum "myShoggoth.cabal" }}
            - stack-work-
      - run:
          name: Build site executable
          command: |
            stack setup
            stack build
      - save_cache:
          paths:
            - ~/myshoggoth/.stack-work
            - /root/.stack/
          key: v1-stack-work-{{ checksum "myShoggoth.cabal" }}
      - deploy:
          name: Deploy master to Github Pages
          command: |
            git config --global user.email robots@circleci.com
            git config --global user.name CircleCI
            stack exec myShoggoth rebuild
            git checkout master
            git pull --rebase
            # Overwrite existing files with new files
            cp -a _site/. .
            #  Commit
            git add --all
            git commit -m "[`date '+%F %T %Z'`] New release"
            # Push
            git push origin master:master
